import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst } from 'workbox-strategies';

declare const self: ServiceWorkerGlobalScope;

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache game assets (images, sounds, tilemaps) with a// Cache-first for local placeholders and textures
registerRoute(
    ({ request }: { request: Request }) => request.destination === 'image',
    new CacheFirst({
        cacheName: 'assets-cache',
    })
);

// Network-first for game config and core scripts
registerRoute(
    ({ request }: { request: Request }) => request.destination === 'script' || request.destination === 'document',
    new NetworkFirst({
        cacheName: 'core-cache',
    })
);
